services:
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/task-api
    environment:
      - DATABASE_URL
      - API_KEY    
    depends_on:
      - db
    entrypoint: ["tail", "-f", "/dev/null"]
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD

volumes:
  db:
    driver: local
