services:
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL
      - API_KEY    
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - PGUSER
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:
    driver: local
